# Generated by Django 3.2.7 on 2021-10-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_supportticket'),
        ('account', '0003_account_is_able_for_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='supper_packages',
            field=models.ManyToManyField(related_name='super_pack', to='profile_app.Package'),
        ),
    ]
