# Generated by Django 3.2.7 on 2021-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdAmount', models.FloatField(default=0)),
                ('trxAmount', models.FloatField(default=0)),
                ('ethAmount', models.FloatField(default=0)),
                ('btcAmount', models.FloatField(default=0)),
            ],
        ),
    ]
