# Generated by Django 3.2.7 on 2021-09-30 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupees'), ('TRX', 'Tron Currency'), ('ETH', 'Etherium Currency'), ('BTC', 'Bitcoin Currency')], max_length=10)),
                ('address', models.CharField(default='', max_length=50)),
                ('txId', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('dollarAmount', models.FloatField(default=0)),
                ('inrAmount', models.FloatField(default=0)),
                ('trxAmount', models.FloatField(default=0)),
                ('ethAmount', models.FloatField(default=0)),
                ('btcAmount', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
