# Generated by Django 3.2.7 on 2021-09-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_auto_20210924_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrecord',
            name='fundType',
            field=models.CharField(choices=[('TFS', 'Transfer'), ('ADD', 'Added From System')], default='ADD', max_length=17),
        ),
    ]
