# Generated by Django 3.2.7 on 2021-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_fund_previoud_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='system_added',
            field=models.BooleanField(default=False),
        ),
    ]
