# Generated by Django 3.2.7 on 2021-10-11 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0010_levelincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupees'), ('TRX', 'Tron Currency'), ('ETH', 'Etherium Currency'), ('BTC', 'Bitcoin Currency')], max_length=10)),
                ('address', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('dollarAmount', models.FloatField(default=0)),
                ('cryptoPayment', models.FloatField(default=0)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
