# Generated by Django 3.2.7 on 2021-10-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
